version: '3'

networks:
  project:

services:
  project:
    build:
      context: ./dockerfiles
      dockerfile: nginx.root.dockerfile
    container_name: project_nginx
    ports:
      - "80:80"
    volumes:
      - ./../project:/var/www/html:delegated
    depends_on:
      - php
#      - redis
      - mysql
      - mailhog
      - phpmyadmin
    networks:
      - project

  mysql:
    image: mariadb:10.6
    container_name: project_mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Europe/Moscow
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    links:
      - mysql:db
    ports:
      - 9090:80
    environment:
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql
    networks:
      - project

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: project_php
    ports:
      - "9000:9000"
    volumes:
      - ./../project:/var/www/html:delegated
    networks:
      - project

#  redis:
#    image: redis:alpine
#    container_name: project_redis
#    ports:
#      - "6379:6379"
#    networks:
#      - project

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: project_composer
    volumes:
      - ./../project:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - project

  npm:
    image: node:13.7
    container_name: project_npm
    volumes:
      - ./../project:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - project

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: project_artisan
    volumes:
      - ./../project:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - project

  mailhog:
    image: mailhog/mailhog:latest
    container_name: project_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - project
